on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: inject environment variables to keymaps
        env:
          SUBMASTER_MACRO_BINDINGS: ${{ secrets.SUBMASTER_MACRO_BINDINGS }}
          MASTER_MACRO_BINDINGS: ${{ secrets.MASTER_MACRO_BINDINGS }}
        run: |
          sed -i "s#// __SUBMASTER_MACRO_BINDINGS__#${SUBMASTER_MACRO_BINDINGS}#" config/cradio.keymap
          sed -i "s#// __MASTER_MACRO_BINDINGS__#${MASTER_MACRO_BINDINGS}#" config/cradio.keymap
      - name: Build User Config
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
